/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "Caramel": "焦糖",
    "Scorched": "烧焦",
    "Fallout Warning (Minimal Wear": "沉降警告（最小磨损",
    "\nTotal Money Earned": "\n总收入",
    "| \nDrop Frequency": "| \n掉落频率",
    "| All image assets property of Valve": "| 价值的所有图像资源属性",
    "| Buy Idlebot (-1s Drop Frequency (Min 4s)": "| 购买 放置机器人（-1秒 掉落频率（最少 4 秒）",
    "| Buy Idlebot (-1s Drop Frequency (Min 4s) )": "| 购买 放置机器人（-1秒 掉落频率（最少 4 秒） )",
    "| Buy Smurf (+5 Inventory Slots": "| 购买小精灵（+5 库存插槽",
    "| Inventory Space": "| 库存空间",
    "| Skill Level": "| 技能等级 Level",
    "Jungle Spray": "丛林喷雾",
    "Safari Mesh": "旅行网",
    "Classified": "分类",
    "Consumer Grade": "消费级",
    "Covert": "涂装",
    "Reset Save": "重置游戏",
    "Sell All": "全部出售",
    "Open Case": "打开箱子",
    "Money": "钱",
    "Mil-Spec": "军用规格",
    "Knives": "刀",
    "Keys": "钥匙",
    "Load": "加载",
    "Inventory": "库存",
    "Industrial Grade": "工业级",
    "EXP": "经验值",
    "EXP/S | \nYou have idled for": "经验值/秒 | \n你放置了",
    "Cases": "宝箱",
    "CaliCamo": "卡利迷彩",
    "Fallout Warning": "辐射警告",
    "Stats": "统计",
    "Total Weapons Owned": "拥有的总武器",
    "Gator Mesh": "鳄鱼网",
    "Sand Dune": "沙丘",
    "Restricted": "限制级",
    "Contractor": "承包商",
    "Join the Steam Group!": "加入Steam群组！",
    "Jungle": "丛林",
    "Groundwater": "地下水",
    "Elite": "精英",
    "Galil AR I Sandstorm": "Galil AR I 沙尘暴",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
//    "Winter Offensive Case": "冬季进攻宝箱",
//    "Huntsman Case": "猎人宝箱",
//    "Breakout Case": "爆裂宝箱",
//    "Chroma Case": "彩色宝箱",
    "Winter Offensive Case": "Winter Offensive Case",
    "Huntsman Case": "Huntsman Case",
    "Breakout Case": "Breakout Case",
    "Chroma Case": "Chroma Case",
    "eSports 2014 Summer Case": "eSports 2014 Summer Case",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "UMP-45 I ": "UMP-45 I ",
    "XM1014 I ": "XM1014 I ",
    "| Version ": "| 版本号 ",
    "AK-47 I ": "AK-47 I ",
    "Sell Cases (": "出售箱子 (",
    "Negev I ": "Negev I ",
    "Buy ": "购买 ",
    "Desert Eagle I ": "沙漠之鹰 I",
    "Five-SeveN I ": "Five-SeveN I ",
    "M249 I ": "M249 I ",
    "Glock-18 I ": "",
    "MP7 I ": "",
    "New Drop: ": "新掉落: ",
    "Silver ": "白银 ",
    "SG 553 I ": "",
    "P250 I ": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    " (Field-Tested": "（久经沙场",
    " (Battle-Scarred": "（战痕累累",
    " (Minimal Wear": "（最小磨损",
    " (Factory New": "(全新出厂",
    " (Well-Worn": "（磨损严重",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) €$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Key \((.+) €$/, '钥匙 \($1 €'],
    [/^Chroma Case \((.+) €$/, 'Chroma Case \($1 €'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);